name = "noobz"
main = "index.js"

[[bindings]]
type = "secret"
name = "VLESS_SERVER_URL"
text = "vless-server.com"

[[bindings]]
type = "secret"
name = "VMESS_SERVER_URL"
text = "vmess-server.com"

[[bindings]]
type = "secret"
name = "TROJAN_SERVER_URL"
text = "trojan-server.com"

[[bindings]]
type = "secret"
name = "SOCKS5_SERVER_URL"
text = "socks5-server.com"
