name = "noobz-proxy-worker"
main = "index.js"
compatibility_date = "2023-12-23"  # Sesuaikan dengan tanggal yang sesuai

workers_dev = true

# Definisikan environment untuk produksi
[env.production]
route = "https://noobzvpn.pages.dev/*"  # Ganti dengan domain Cloudflare Worker Anda

# Definisikan variabel-variabel untuk server backend yang digunakan
[[vars]]
name = "VLESS_SERVER_URL"
value = "vless-server.com"  # Ganti dengan URL server VLESS

[[vars]]
name = "VMESS_SERVER_URL"
value = "vmess-server.com"  # Ganti dengan URL server VMess

[[vars]]
name = "TROJAN_SERVER_URL"
value = "trojan-server.com"  # Ganti dengan URL server Trojan

[[vars]]
name = "SOCKS5_SERVER_URL"
value = "socks5-server.com"  # Ganti dengan URL server SOCKS5

# Port yang diizinkan oleh Cloudflare untuk TLS (HTTPS) dan Non-TLS (HTTP)
[[vars]]
name = "AVAILABLE_TLS_PORTS"
value = "443,8443,4433"  # Port untuk TLS (HTTPS)

[[vars]]
name = "AVAILABLE_NON_TLS_PORTS"
value = "80,8080,8880"  # Port untuk Non-TLS (HTTP)

# Secret yang digunakan untuk akses yang lebih aman
[[bindings]]
type = "secret"
name = "VLESS_SERVER_URL"
text = "vless-server.com"  # Ganti dengan URL server VLESS yang benar

[[bindings]]
type = "secret"
name = "VMESS_SERVER_URL"
text = "vmess-server.com"  # Ganti dengan URL server VMess yang benar

[[bindings]]
type = "secret"
name = "TROJAN_SERVER_URL"
text = "trojan-server.com"  # Ganti dengan URL server Trojan yang benar

[[bindings]]
type = "secret"
name = "SOCKS5_SERVER_URL"
text = "socks5-server.com"  # Ganti dengan URL server SOCKS5 yang benar

# Menentukan alamat untuk UUID yang digunakan
[[bindings]]
type = "secret"
name = "UUID"
text = "1b6c1745-992e-4aac-8685-266c090e50ea"  # Ganti dengan UUID yang sesuai
