name = "proxy-worker"  # Nama aplikasi/worker Anda
main = "index.js"      # File entry utama yang akan dieksekusi oleh Worker

type = "javascript"    # Jenis worker yang digunakan (javascript)

# Tentukan pengaturan untuk environment development dan production
[env.production]
route = "https://your-domain.com/*"  # Tentukan rute untuk worker di production (misalnya domain atau subdomain)
zone_id = "your-zone-id"  # ID zona Cloudflare Anda

[env.dev]
route = "http://localhost:8787/*"  # Rute untuk pengembangan lokal
zone_id = "your-zone-id"

# Menentukan API Worker di Cloudflare
[workers]
kv_namespaces = []
vars = {}

# Untuk mendukung berbagai protokol proxy (Trojan, V2Ray), SOCKS5, dan DoH
[[bindings]]
type = "secret"
name = "DOH_SERVER"
text = "https://dns.google/dns-query"  # Contoh server DoH, bisa diganti sesuai preferensi

[[bindings]]
type = "secret"
name = "SOCKS5_SERVER"
text = "socks5://your-socks5-server:1080"  # Alamat server SOCKS5 Anda

[[bindings]]
type = "secret"
name = "PROXY_SERVER"
text = "http://your-proxy-server.com"  # Alamat server proxy Anda (misalnya Trojan atau V2Ray)

# Menambahkan UUID atau password untuk identifikasi atau otentikasi
[[bindings]]
type = "secret"
name = "UUID"
text = "f091c96d-419a-4c69-994c-6944182c46af"  # UUID yang digunakan untuk konfigurasi unik

[[bindings]]
type = "secret"
name = "PASSWORD"
text = "your-secure-password"  # Password untuk otentikasi atau konfigurasi lainnya
